
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class datamuzakki extends javax.swing.JFrame {
    
    private void showData(){

    DefaultTableModel tb = new DefaultTableModel();

    tb.addColumn("ID Muzakki");
    tb.addColumn("Nama Muzakki");
    tb.addColumn("Jenis Kelamin");
    tb.addColumn("Alamat");
    tb.addColumn("No. Telp");
    
    try {
        
        
        String sql = "SELECT * FROM tbmuzakki WHERE id_muzakki='" + 
                txtcari.getText() +"%'" + "or nama_muzakki like '%" +txtcari.getText()+"%'";
        Connection con = koneksi.getKoneksi();
        Statement sta = (Statement) con.createStatement();
        ResultSet res = sta.executeQuery(sql);
        while (res.next()) {
            tb.addRow(new Object[]{ res.getString(1),
            res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
        }
        tabmuzakki.setModel(tb);
    
    } catch (Exception e) {
  
    }
    } 
    public void clearForm() {
        idmuzakki.setText(null);
        NamaMuzakki.setText(null);
        txtbutton.clearSelection();
        alamat.setText(null);
        notelp.setText(null);
    
    }
    


          
    public datamuzakki() {
        initComponents();
        this.setLocationRelativeTo(null);
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtbutton = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabmuzakki = new javax.swing.JTable();
        IDMuzakki = new javax.swing.JPanel();
        idmuzakki = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        NamaMuzakki = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        bersihkan = new javax.swing.JButton();
        lakilaki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        notelp = new javax.swing.JTextField();
        laporanpenyaluran = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        print = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PENDATAAN MUZAKKI");
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PENDATAAN MUZAKKI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        tabmuzakki.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Muzakki", "Nama Muzakki", "Jenis Kelamin", "Alamat", "No.Telp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabmuzakki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabmuzakkiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabmuzakki);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 970, 130));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("ID Muzakki");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Nama Muzakki");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Alamat");

        hapus.setText("Hapus");
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        bersihkan.setText("Bersihkan");
        bersihkan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });

        txtbutton.add(lakilaki);
        lakilaki.setText("Laki-Laki");
        lakilaki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtbutton.add(perempuan);
        perempuan.setText("Perempuan");
        perempuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("No. Telp");

        javax.swing.GroupLayout IDMuzakkiLayout = new javax.swing.GroupLayout(IDMuzakki);
        IDMuzakki.setLayout(IDMuzakkiLayout);
        IDMuzakkiLayout.setHorizontalGroup(
            IDMuzakkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IDMuzakkiLayout.createSequentialGroup()
                .addGroup(IDMuzakkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(IDMuzakkiLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(simpan)
                        .addGap(30, 30, 30)
                        .addComponent(hapus)
                        .addGap(34, 34, 34)
                        .addComponent(bersihkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(edit))
                    .addGroup(IDMuzakkiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(IDMuzakkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGroup(IDMuzakkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IDMuzakkiLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(IDMuzakkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idmuzakki, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NamaMuzakki, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(IDMuzakkiLayout.createSequentialGroup()
                                        .addComponent(lakilaki)
                                        .addGap(18, 18, 18)
                                        .addComponent(perempuan))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IDMuzakkiLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(notelp, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        IDMuzakkiLayout.setVerticalGroup(
            IDMuzakkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IDMuzakkiLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(IDMuzakkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idmuzakki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(IDMuzakkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NamaMuzakki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(IDMuzakkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lakilaki)
                    .addComponent(perempuan))
                .addGap(18, 18, 18)
                .addGroup(IDMuzakkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(15, 15, 15)
                .addGroup(IDMuzakkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(notelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(IDMuzakkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(hapus)
                    .addComponent(edit)
                    .addComponent(bersihkan))
                .addGap(37, 37, 37))
        );

        getContentPane().add(IDMuzakki, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 430, 340));

        laporanpenyaluran.setBackground(new java.awt.Color(102, 0, 255));
        laporanpenyaluran.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        laporanpenyaluran.setForeground(new java.awt.Color(255, 255, 255));
        laporanpenyaluran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-left-48 - Copy.png"))); // NOI18N
        laporanpenyaluran.setText("Lanjut Penyaluran");
        laporanpenyaluran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanpenyaluran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpenyaluranActionPerformed(evt);
            }
        });
        getContentPane().add(laporanpenyaluran, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 600, -1, -1));

        kembali.setBackground(new java.awt.Color(102, 0, 255));
        kembali.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-left-48.png"))); // NOI18N
        kembali.setText("Kembali");
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        print.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo print.png"))); // NOI18N
        print.setText("Print Laporan");
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 377, 220, -1));

        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-outline-filled.png"))); // NOI18N
        btncari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        getContentPane().add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 380, 50, 50));

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 200, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CARI ID");
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgpurplemasjid.jpg"))); // NOI18N
        jLabel1.setText("Zakat Tabungan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-640, -180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laporanpenyaluranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpenyaluranActionPerformed
        // TODO add your handling code here:
        new pendataan().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_laporanpenyaluranActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        new pendataan().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String idmuz = idmuzakki.getText();
        String namamuz = NamaMuzakki.getText();
        String jk = null;
        String address = alamat.getText();
        String numb = notelp.getText();
        DefaultTableModel tbl = (DefaultTableModel) tabmuzakki.getModel();
        Connection con = koneksi.getKoneksi();
       
     
        if (lakilaki.isSelected()) {
            jk = "Laki-Laki";
        
        } else if (perempuan.isSelected()){
            jk = "Perempuan";
        }
        
        
        
        try {                                       
            Statement sta = (Statement) con.createStatement();
            String sql = "SELECT * FROM tbmuzakki WHERE id_muzakki='" + idmuz 
                    + "'";
            
            ResultSet res = sta.executeQuery(sql);
            
            if(res.next()){
                
                JOptionPane.showMessageDialog(null,"ID Sudah Terdaftar", "Kesalahan",
                            JOptionPane.INFORMATION_MESSAGE);
                    clearForm();
            
            }
            else {
                try {
            
            String query = "INSERT INTO `tbmuzakki`(`id_muzakki`, `nama_muzakki`, `jenis_kelamin`, `alamat`, `notelp`) VALUES ('" +idmuz+
                    "','"+namamuz +
                    "','"+jk+
                    "','"+address+
                    "','"+numb+"')";
            
            PreparedStatement ps = (PreparedStatement)con.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan");
            clearForm();
            showData();
            
        } catch (SQLException ex) {
            Logger.getLogger(datamuzakki.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            }
        
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(datamuzakki.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_simpanActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportmuzakki.jasper"), 
                    null, koneksi.getKoneksi());
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            
        }
    }//GEN-LAST:event_printActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String idmuz = idmuzakki.getText();
        String namamuz = NamaMuzakki.getText();
        String jk = null;
        String address = alamat.getText();
        String numb = notelp.getText();
        DefaultTableModel tbl = (DefaultTableModel) tabmuzakki.getModel();
        Connection con = koneksi.getKoneksi();

        
        if (lakilaki.isSelected()) {
            jk = "Laki-Laki";
        
        } else if (perempuan.isSelected()){
            jk = "Perempuan";
        }
        
        
        
        try {                                       
            String query = "UPDATE `tbmuzakki` SET `id_muzakki`='" + idmuz
                    + "', `nama_muzakki`='"+namamuz
                    + "', `jenis_kelamin`='"+jk
                    + "', `alamat`='"+ address
                    + "', `notelp`='"+numb
                    +"' WHERE id_muzakki='"+idmuz+"'";
            
            PreparedStatement ps = (PreparedStatement)con.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan");
            clearForm();
            showData();
            
        } catch (SQLException ex) {
            Logger.getLogger(datamuzakki.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_editActionPerformed

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_bersihkanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        
        try {
            String sql = "DELETE FROM tbmuzakki WHERE id_muzakki='" + idmuzakki.getText()+"'";
            Connection con = koneksi.getKoneksi();
            PreparedStatement ps = (PreparedStatement)con.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Hapus Data");
            
        } catch (SQLException ex) {
            Logger.getLogger(datamuzakki.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
        clearForm();
    }//GEN-LAST:event_hapusActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM tbmuzakki WHERE id_muzakki='" + 
                txtcari.getText() +"%'" + "or nama_muzakki like '%" +txtcari.getText()+"%'";
            Connection con = koneksi.getKoneksi();
            PreparedStatement ps = (PreparedStatement)con.prepareStatement(sql);
            ps.execute();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(datamuzakki.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
        clearForm();
        
    }//GEN-LAST:event_btncariActionPerformed

    private void tabmuzakkiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabmuzakkiMouseClicked
        // TODO add your handling code here:
        int row =  tabmuzakki.rowAtPoint(evt.getPoint());
        String id_muzakki = tabmuzakki.getValueAt(row, 0).toString();
        idmuzakki.setText(id_muzakki);
        
        String nama = tabmuzakki.getValueAt(row, 1).toString();
        NamaMuzakki.setText(nama);
        
        if ("Perempuan".equals(tabmuzakki.getValueAt(row, 2).toString())){
                perempuan.setSelected(true);
        }else {
                lakilaki.setSelected(true);
        }
        
        String al = tabmuzakki.getValueAt(row, 3).toString();
        alamat.setText(al);
        
        String no = tabmuzakki.getValueAt(row, 4).toString();
        notelp.setText(no);
    }//GEN-LAST:event_tabmuzakkiMouseClicked

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datamuzakki().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IDMuzakki;
    private javax.swing.JTextField NamaMuzakki;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton bersihkan;
    private javax.swing.JButton btncari;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idmuzakki;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kembali;
    private javax.swing.JRadioButton lakilaki;
    private javax.swing.JButton laporanpenyaluran;
    private javax.swing.JTextField notelp;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JButton print;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabmuzakki;
    private javax.swing.ButtonGroup txtbutton;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
