
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class datamustahik extends javax.swing.JFrame {

    private void showData(){
    DefaultTableModel tb = new DefaultTableModel();

    tb.addColumn("ID Mustahik");
    tb.addColumn("Nama Mustahik");
    tb.addColumn("Jenis Mustahik");
    tb.addColumn("Jenis Kelamin");
    tb.addColumn("Alamat");
    tb.addColumn("No. Telp");
    
    try {
        
        
        String sql = "SELECT * FROM tbmustahik WHERE id_mustahik='" + 
                txtcari.getText() +"%'" + "or nama_mustahik like '%" +txtcari.getText()+"%'";
        Connection con = koneksi.getKoneksi();
        Statement sta = (Statement) con.createStatement();
        ResultSet res = sta.executeQuery(sql);
        while (res.next()) {
            tb.addRow(new Object[]{ res.getString(1),
            res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6)});
        }
        tabmus.setModel(tb);
    
    } catch (Exception e) {
  
    }
    } 
    
    public void clearForm() {
        idmustahik.setText(null);
        namamustahik.setText(null);
        btngroup.clearSelection();
        jenismustahik.setSelectedIndex(0);
        alamat.setText(null);
        notelp.setText(null);
    
    }

    public datamustahik() {
        initComponents();
        this.setLocationRelativeTo(null);
        showData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btngroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabmus = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        idmustahik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        namamustahik = new javax.swing.JTextField();
        jenismustahik = new javax.swing.JComboBox<>();
        hapus = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        bersihkan = new javax.swing.JButton();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        notelp = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PENDATAAN MUSTAHIK");
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PENDATAAN MUSTAHIK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        tabmus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Mustahik", "Nama Mustahik", "Jenis Mustahik", "Jenis Kelamin", "Alamat", "No.Telp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabmus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabmusMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabmus);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 970, 130));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("ID Mustahik");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Nama Mustahik");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Mustahik");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Alamat");

        jenismustahik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Mustahik", "Fisabilillah", "Ibnu Sabil", "Fakir", "Miskin", "Mualaf", "Amil", "Hamba Sahaya", "Gharim" }));
        jenismustahik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        hapus.setText("Hapus");
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        bersihkan.setText("Bersihkan");
        bersihkan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });

        btngroup.add(laki);
        laki.setText("Laki-Laki");
        laki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btngroup.add(perempuan);
        perempuan.setText("Perempuan");
        perempuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("No. Telp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(simpan)
                        .addGap(30, 30, 30)
                        .addComponent(hapus)
                        .addGap(34, 34, 34)
                        .addComponent(bersihkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(edit))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenismustahik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idmustahik, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namamustahik, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(laki)
                                        .addGap(18, 18, 18)
                                        .addComponent(perempuan))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(notelp, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idmustahik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(namamustahik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(laki)
                    .addComponent(perempuan))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jenismustahik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(notelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(hapus)
                    .addComponent(edit)
                    .addComponent(bersihkan))
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 430, 330));

        next.setBackground(new java.awt.Color(102, 0, 255));
        next.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-left-48 - Copy.png"))); // NOI18N
        next.setText("Lanjut Penyaluran");
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 600, -1, -1));

        back.setBackground(new java.awt.Color(102, 0, 255));
        back.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-left-48.png"))); // NOI18N
        back.setText("Kembali");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-outline-filled.png"))); // NOI18N
        btncari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        getContentPane().add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, 50, 50));
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 200, 50));

        print.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo print.png"))); // NOI18N
        print.setText("Print Laporan");
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 240, 50));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgpurplemasjid.jpg"))); // NOI18N
        jLabel1.setText("Zakat Tabungan");
        jLabel1.setDisabledIcon(null);
        jLabel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-640, -180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CARI ID");
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgpurplemasjid.jpg"))); // NOI18N
        jLabel9.setText("Zakat Tabungan");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-640, -180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        new penyaluranzakat().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new pendataan().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String idmus = idmustahik.getText();
        String namamus = namamustahik.getText();
        String jk = null;
        String jmus = (String) jenismustahik.getSelectedItem();
        String address = alamat.getText();
        String numb = notelp.getText();
        DefaultTableModel tbl = (DefaultTableModel) tabmus.getModel();
        Connection con = koneksi.getKoneksi();

        
        if (laki.isSelected()) {
            jk = "Laki-Laki";
        
        } else if (perempuan.isSelected()){
            jk = "Perempuan";
        }
        
        try {                                       
            Statement sta = (Statement) con.createStatement();
            String sql = "SELECT * FROM tbmustahik WHERE id_mustahik='" + idmus 
                    + "'";
            
            ResultSet res = sta.executeQuery(sql);
            
            if(res.next()){
                
                JOptionPane.showMessageDialog(null,"ID Sudah Terdaftar", "Kesalahan",
                            JOptionPane.INFORMATION_MESSAGE);
                    clearForm();
            
            }
            else {
                try {
            
            String query = "INSERT INTO `tbmustahik`(`id_mustahik`,"
                    + " `nama_mustahik`, `jenis_kelamin`, `jenis_mustahik`, `alamat`, `notelp`) "
                    + "VALUES ('" +idmus+
                    "','"+namamus +
                    "','"+jk+
                    "','"+jmus+
                    "','"+address+
                    "','"+numb+"')";
            
            PreparedStatement ps = (PreparedStatement)con.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan");
            clearForm();
            showData();
            
        } catch (SQLException ex) {
            
        }
            
            
            }
        
        } 
        
        catch (SQLException ex) {
           
        }
                
            

    }//GEN-LAST:event_simpanActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            // TODO add your handling code here:
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportmustahik.jasper"),
                    null, koneksi.getKoneksi());
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            
        }
        
        
    }//GEN-LAST:event_printActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        
        String idmus = idmustahik.getText();
        String namamus = namamustahik.getText();
        String jk = null;
        String jmus = (String) jenismustahik.getSelectedItem();;
        String address = alamat.getText();
        String numb = notelp.getText();
        DefaultTableModel tbl = (DefaultTableModel) tabmus.getModel();
        Connection con = koneksi.getKoneksi();
        
        
        if (laki.isSelected()) {
            jk = "Laki-Laki";
        
        } else if (perempuan.isSelected()){
            jk = "Perempuan";
        }
        

        try {                                       
            
                
            
            String query = "UPDATE `tbmustahik` SET `id_mustahik`='" + idmus
                    + "', `nama_mustahik`='"+namamus
                    + "', `jenis_kelamin`='"+jk
                    + "', `jenis_mustahik`='"+jmus
                    + "', `alamat`='"+ address
                    + "', `notelp`='"+numb
                    +"' WHERE id_mustahik='"+idmus+"'";
            
            PreparedStatement ps = (PreparedStatement)con.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Mengedit");
            clearForm();
            showData();
            
        } 
        
        catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_editActionPerformed

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_bersihkanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM tbmustahik WHERE id_mustahik='" + idmustahik.getText()+"'";
            Connection con = koneksi.getKoneksi();
            PreparedStatement ps = (PreparedStatement)con.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Hapus Data");
            
        } catch (SQLException ex) {
            Logger.getLogger(datamustahik.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
        clearForm();
    }//GEN-LAST:event_hapusActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM tbmustahik WHERE id_mustahik='" + 
                txtcari.getText() +"%'" + "or nama_mustahik like '%" +txtcari.getText()+"%'";
            Connection con = koneksi.getKoneksi();
            PreparedStatement ps = (PreparedStatement)con.prepareStatement(sql);
            ps.execute();
            
            
        } catch (SQLException ex) {
            
        }
        showData();

    }//GEN-LAST:event_btncariActionPerformed

    private void tabmusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabmusMouseClicked
        // TODO add your handling code here:
        int row =  tabmus.rowAtPoint(evt.getPoint());
        String id_mus = tabmus.getValueAt(row, 0).toString();
        idmustahik.setText(id_mus);
        
        String nama = tabmus.getValueAt(row, 1).toString();
        namamustahik.setText(nama);
        
        if ("Perempuan".equals(tabmus.getValueAt(row, 2).toString())){
                perempuan.setSelected(true);
        }else {
                laki.setSelected(true);
        }
        
        String  jm = tabmus.getValueAt(row, 3).toString();
        jenismustahik.setSelectedItem(jm);
        
        String al = tabmus.getValueAt(row, 4).toString();
        alamat.setText(al);
        
        String no = tabmus.getValueAt(row, 5).toString();
        notelp.setText(no);
        
    }//GEN-LAST:event_tabmusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datamustahik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton back;
    private javax.swing.JButton bersihkan;
    private javax.swing.JButton btncari;
    private javax.swing.ButtonGroup btngroup;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idmustahik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jenismustahik;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField namamustahik;
    private javax.swing.JButton next;
    private javax.swing.JTextField notelp;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JButton print;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabmus;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
