

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fitrah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        penghasilan = new javax.swing.JButton();
        emas = new javax.swing.JButton();
        dagang = new javax.swing.JButton();
        tabungan = new javax.swing.JButton();
        back = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Zakat");
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fitrah.setBackground(new java.awt.Color(0,0,0,80));
        fitrah.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        fitrah.setForeground(new java.awt.Color(255, 255, 255));
        fitrah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ketupat.jpg"))); // NOI18N
        fitrah.setText("Zakat Fitrah");
        fitrah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fitrah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitrahActionPerformed(evt);
            }
        });
        getContentPane().add(fitrah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KALKULATOR ZAKAT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        penghasilan.setBackground(new java.awt.Color(0,0,0,80)
        );
        penghasilan.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        penghasilan.setForeground(new java.awt.Color(255, 255, 255));
        penghasilan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneyy.png"))); // NOI18N
        penghasilan.setText("Zakat Penghasilan");
        penghasilan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        penghasilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penghasilanActionPerformed(evt);
            }
        });
        getContentPane().add(penghasilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        emas.setBackground(new java.awt.Color(0,0,0,80)
        );
        emas.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        emas.setForeground(new java.awt.Color(255, 255, 255));
        emas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldbar.jpg"))); // NOI18N
        emas.setText("Zakat Emas");
        emas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emasActionPerformed(evt);
            }
        });
        getContentPane().add(emas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 260, -1));

        dagang.setBackground(new java.awt.Color(0,0,0,80)
        );
        dagang.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        dagang.setForeground(new java.awt.Color(255, 255, 255));
        dagang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dagang.png"))); // NOI18N
        dagang.setText("Zakat Perdagangan");
        dagang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dagang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dagangActionPerformed(evt);
            }
        });
        getContentPane().add(dagang, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        tabungan.setBackground(new java.awt.Color(0,0,0,80)
        );
        tabungan.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        tabungan.setForeground(new java.awt.Color(255, 255, 255));
        tabungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tabungan.png"))); // NOI18N
        tabungan.setText("Zakat Tabungan");
        tabungan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabunganActionPerformed(evt);
            }
        });
        getContentPane().add(tabungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        back.setBackground(new java.awt.Color(102, 0, 255));
        back.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-left-48.png"))); // NOI18N
        back.setText("Kembali");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        next.setBackground(new java.awt.Color(102, 0, 255));
        next.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-left-48 - Copy.png"))); // NOI18N
        next.setText("Lanjut Pendataan");
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgpurplemasjid.jpg"))); // NOI18N
        jLabel1.setText("Zakat Tabungan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-640, -180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fitrahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitrahActionPerformed
        // TODO add your handling code here:
        new zakatfitrah().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_fitrahActionPerformed

    private void penghasilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penghasilanActionPerformed
        // TODO add your handling code here:
        new zakatpenghasilan().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_penghasilanActionPerformed

    private void emasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emasActionPerformed
        // TODO add your handling code here:
        new zakatemas().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_emasActionPerformed

    private void tabunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabunganActionPerformed
        // TODO add your handling code here:
        new zakattabungan().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_tabunganActionPerformed

    private void dagangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dagangActionPerformed
        // TODO add your handling code here:
        new zakatperdagangan().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_dagangActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        new pendataan().setVisible(true);this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton dagang;
    private javax.swing.JButton emas;
    private javax.swing.JButton fitrah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton next;
    private javax.swing.JButton penghasilan;
    private javax.swing.JButton tabungan;
    // End of variables declaration//GEN-END:variables
}
