

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class pendataan extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public pendataan() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**    * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        datamustahik = new javax.swing.JButton();
        datamuzakki = new javax.swing.JButton();
        datazakat = new javax.swing.JButton();
        back = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PENDATAAN ");
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PENDATAAN ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        datamustahik.setBackground(new java.awt.Color(255, 204, 204));
        datamustahik.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        datamustahik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/muslim.png"))); // NOI18N
        datamustahik.setText("Data Mustahik");
        datamustahik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        datamustahik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datamustahikActionPerformed(evt);
            }
        });
        getContentPane().add(datamustahik, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 290, 120));

        datamuzakki.setBackground(new java.awt.Color(255, 204, 204));
        datamuzakki.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        datamuzakki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/muslim.png"))); // NOI18N
        datamuzakki.setText("Data Muzakki");
        datamuzakki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        datamuzakki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datamuzakkiActionPerformed(evt);
            }
        });
        getContentPane().add(datamuzakki, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 290, 120));

        datazakat.setBackground(new java.awt.Color(255, 204, 204));
        datazakat.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        datazakat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zakat.jpg"))); // NOI18N
        datazakat.setText("Data Zakat");
        datazakat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        datazakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datazakatActionPerformed(evt);
            }
        });
        getContentPane().add(datazakat, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 290, 120));

        back.setBackground(new java.awt.Color(102, 0, 255));
        back.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-left-48.png"))); // NOI18N
        back.setText("Kembali");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        next.setBackground(new java.awt.Color(102, 0, 255));
        next.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-left-48 - Copy.png"))); // NOI18N
        next.setText("Lanjut Penyaluran");
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgpurplemasjid.jpg"))); // NOI18N
        jLabel1.setText("Zakat Tabungan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-640, -180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datamustahikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datamustahikActionPerformed
        // TODO add your handling code here:
        new datamustahik().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_datamustahikActionPerformed

    private void datazakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datazakatActionPerformed
        // TODO add your handling code here:
        new datazakat().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_datazakatActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        new penyaluranzakat().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    private void datamuzakkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datamuzakkiActionPerformed
        // TODO add your handling code here:
        new datamuzakki().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_datamuzakkiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pendataan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton datamustahik;
    private javax.swing.JButton datamuzakki;
    private javax.swing.JButton datazakat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
