
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class penyaluranzakat extends javax.swing.JFrame {
    
    private void showData(){
    DefaultTableModel tb = new DefaultTableModel();

    tb.addColumn("ID Penyaluran");
    tb.addColumn("Tanggal Penyaluran");
    tb.addColumn("Nama Mustahik");
    tb.addColumn("Alamat");
    tb.addColumn("No. Telp");
    tb.addColumn("Besaran Zakat");
    
    try {
        
        
        String sql = "SELECT * FROM tbsalur WHERE id_salur='" + 
                txtcari.getText() +"%'"+"or nama_mustahik like '%" +txtcari.getText()+"%'";
        Connection con = koneksi.getKoneksi();
        Statement sta = (Statement) con.createStatement();
        ResultSet res = sta.executeQuery(sql);
        while (res.next()) {
            tb.addRow(new Object[]{ res.getString(1),
            res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6)});
        }
        tabsalur.setModel(tb);
    
    } catch (Exception e) {
  
    }
    } 
    
    public void clearForm() {
        besarzakat.setText(null);
        idsalur.setText(null);
        namacombo.setSelectedIndex(0);
        idcom.setSelectedIndex(0);
        alamat.setText(null);
        notelp.setText(null);
    
    }
    public void showCombo(){
       
        try {
            String sql = "SELECT * FROM tbmustahik" ;
            Connection con = koneksi.getKoneksi();
            Statement sta = (Statement) con.createStatement();
            ResultSet res = sta.executeQuery(sql);
            while (res.next()) {
            namacombo.addItem(res.getString("nama_mustahik"));
            
            
        }
        } catch (SQLException ex) {
           
        }
        try {
            String sql = "SELECT * FROM datazakat WHERE status_penyaluran='Belum Disalurkan'" ;
            Connection con = koneksi.getKoneksi();
            Statement sta = (Statement) con.createStatement();
            ResultSet res = sta.executeQuery(sql);
            while (res.next()) {
            idcom.addItem(res.getString("id_zakat"));
            
            
        }
        } catch (SQLException ex) {
           
        }
        
    
    }
    
    public void showTgl(){
        
    Date dt = new Date();
    SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
    tanggal.setText(s.format(dt));
    
    }
    

    /**
     * Creates new form Kalkulator
     */
    public penyaluranzakat() {
        initComponents();
        this.setLocationRelativeTo(null);
        showData();
        showCombo();
        showTgl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabsalur = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        besarzakat = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        bersihkan = new javax.swing.JButton();
        notelp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idsalur = new javax.swing.JTextField();
        tanggal = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        namacombo = new javax.swing.JComboBox<>();
        idcom = new javax.swing.JComboBox<>();
        pendatan = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        print = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PENYALURAN ZAKAT");
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PENYALURAN ZAKAT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 380, -1));

        tabsalur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Penyaluran", "Tanggal Penyaluran", "Nama Mustahik", "Alamat", "No.Telp", "Besaran Zakat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabsalur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabsalurMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabsalur);
        if (tabsalur.getColumnModel().getColumnCount() > 0) {
            tabsalur.getColumnModel().getColumn(1).setPreferredWidth(3);
            tabsalur.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 980, 130));

        jPanel2.setBackground(new java.awt.Color (0,0,0,80));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Besaran Zakat");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Mustahik");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No.Telp");

        besarzakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                besarzakatActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        bersihkan.setText("Bersihkan");
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Zakat");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal");

        idsalur.setDoubleBuffered(true);

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID Penyaluran");

        namacombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama" }));
        namacombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namacomboMouseClicked(evt);
            }
        });
        namacombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namacomboActionPerformed(evt);
            }
        });

        idcom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID" }));
        idcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(simpan)
                                .addGap(29, 29, 29)
                                .addComponent(hapus)
                                .addGap(26, 26, 26)
                                .addComponent(bersihkan)
                                .addGap(18, 18, 18)
                                .addComponent(edit))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idsalur, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(81, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(alamat, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                .addComponent(notelp))
                            .addComponent(namacombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(besarzakat, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(29, 29, 29)
                                .addComponent(idcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(idsalur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(namacombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(idcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(besarzakat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bersihkan)
                    .addComponent(edit)
                    .addComponent(hapus)
                    .addComponent(simpan))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 600, 310));

        pendatan.setBackground(new java.awt.Color(102, 0, 255));
        pendatan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        pendatan.setForeground(new java.awt.Color(255, 255, 255));
        pendatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-left-48 - Copy.png"))); // NOI18N
        pendatan.setText("Lanjut Pendataan");
        pendatan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pendatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendatanActionPerformed(evt);
            }
        });
        getContentPane().add(pendatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, 240, 50));

        kembali.setBackground(new java.awt.Color(102, 0, 255));
        kembali.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-left-48.png"))); // NOI18N
        kembali.setText("Kembali");
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 180, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CARI ID");
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, -1, -1));

        print.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo print.png"))); // NOI18N
        print.setText("Print Laporan");
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 50));

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 140, 40));

        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-outline-filled.png"))); // NOI18N
        btncari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        getContentPane().add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 370, 40, 40));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgpurplemasjid.jpg"))); // NOI18N
        jLabel1.setText("Zakat Tabungan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-640, -180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pendatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendatanActionPerformed
        // TODO add your handling code here:
        new pendataan().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_pendatanActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String id, tgl,nama, al,no, bz, idc,slr;
        id = idsalur.getText();
        tgl = tanggal.getText();
        nama = (String) namacombo.getSelectedItem();
        al = alamat.getText();
        no = notelp.getText();
        idc =  (String) idcom.getSelectedItem();
        bz = besarzakat.getText();
        slr = "Telah Disalurkan";
        DefaultTableModel tbl = (DefaultTableModel) tabsalur.getModel();
        Connection con = koneksi.getKoneksi();
        
        
        try {   
             
            
            Statement sta = (Statement) con.createStatement();
            String sql = "SELECT * FROM tbsalur WHERE id_salur='" + id
                    + "'";
            ResultSet res = sta.executeQuery(sql);
            
            if(res.next()){
                
                JOptionPane.showMessageDialog(null,"ID Sudah Terdaftar", "Kesalahan",
                            JOptionPane.INFORMATION_MESSAGE);
                clearForm();
            res.close();
            }
            else { 
                try {
            
            String query = "INSERT INTO `tbsalur`(`id_salur`, `tanggal_salur`, `nama_mustahik`, `alamat_mustahik`, `no_telp`, `besar_zakat`) VALUES ('" 
                    +id+
                    "','"+tgl+
                    "','"+nama+
                    "','"+al+
                    "','"+no+
                    "','"+bz+
                    "')";
            
            PreparedStatement ps = (PreparedStatement)con.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan");
            System.out.print(idc);
            try {
            
            String que ="UPDATE `datazakat` SET `status_penyaluran`= '"+slr +"' WHERE id_zakat='"+idc+"'";
            PreparedStatement p = (PreparedStatement)con.prepareStatement(que);
            p.executeUpdate();
            
            
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal");
            }
            res.close();
             
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"Gagal Menyimpan", "Kesalahan",
                            JOptionPane.INFORMATION_MESSAGE);
        }
                 
        
           
        }
        
            } 
        
        
         catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error");
        }
         
       
        
       
           clearForm();
           showData();
        
        
        

            
    }//GEN-LAST:event_simpanActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here: 
        Connection con = koneksi.getKoneksi();
        String idc =  (String) idcom.getSelectedItem();
        try {
            
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportpenyaluran.jasper"), null, koneksi.getKoneksi());
            JasperViewer.viewReport(jp, false);
        } catch (Exception ex) {
            
        }
        
    }//GEN-LAST:event_printActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM tbsalur WHERE id_salur='" +
            txtcari.getText() +"%'" + "or nama_mustahik like '%" +txtcari.getText()+"%'";
            Connection con = koneksi.getKoneksi();
            PreparedStatement ps = (PreparedStatement)con.prepareStatement(sql);
            ps.execute();

        } catch (SQLException ex) {

        }
        showData();
        
    }//GEN-LAST:event_btncariActionPerformed

    private void besarzakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_besarzakatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_besarzakatActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String id, tgl,nama, al,no, bz;
        id = idsalur.getText();
        tgl = tanggal.getText();
        nama = (String) namacombo.getSelectedItem();
        al = alamat.getText();
        no = notelp.getText();
        bz = besarzakat.getText();
        DefaultTableModel tbl = (DefaultTableModel) tabsalur.getModel();
        Connection con = koneksi.getKoneksi();
        
        
        try {    
            
            Statement sta = (Statement) con.createStatement();
            String sql = "SELECT * FROM tbsalur WHERE id_salur='" + id
                    + "'";
            ResultSet res = sta.executeQuery(sql);
            
            while(res.next()){
                
   
            
                try {
            
            String query ="UPDATE `tbsalur` SET `id_salur`='" + id
                    + "', `tanggal_zakat`='"+tgl
                    + "', `nama_mustahik`='"+nama
                    + "', `alamat`='"+al
                    + "', `notelp`='"+no
                    + "', `besar_zakat`='"+ bz
                    +"' WHERE id_zakat='"+id;
            
            PreparedStatement ps = (PreparedStatement)con.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Mengedit");
            
            
            
            
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal Mengedit");
            }
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal");
        }
    }//GEN-LAST:event_editActionPerformed

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_bersihkanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        String id = idsalur.getText();
         try {
            String sql = "DELETE FROM tbsalur WHERE id_salur='" + id+"'";
            Connection con = koneksi.getKoneksi();
            PreparedStatement ps = (PreparedStatement)con.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Hapus Data");
            
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal");}
        showData();
        clearForm();
    }//GEN-LAST:event_hapusActionPerformed

    private void tabsalurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabsalurMouseClicked
        // TODO add your handling code here:
        int row =  tabsalur.rowAtPoint(evt.getPoint());
        String id = tabsalur.getValueAt(row, 0).toString();
        idsalur.setText(id);
        
        String tgl = tabsalur.getValueAt(row, 1).toString();
        tanggal.setText(tgl);
        
        String nama = tabsalur.getValueAt(row, 2).toString();
        namacombo.setSelectedItem(nama);
        
        String  al = tabsalur.getValueAt(row, 3).toString();
        alamat.setText(al);
        
        String no = tabsalur.getValueAt(row, 4).toString();
        notelp.setText(no);
        
        String bz = tabsalur.getValueAt(row, 5).toString();
        besarzakat.setText(bz);

    }//GEN-LAST:event_tabsalurMouseClicked

    private void namacomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namacomboActionPerformed
        // TODO add your handling code here:
        String nama = (String) namacombo.getSelectedItem();
        try {
            String sql = "SELECT * FROM tbmustahik WHERE nama_mustahik='" + 
                    nama+"'";
            Connection con = koneksi.getKoneksi();
            Statement sta = (Statement) con.createStatement();
            ResultSet res = sta.executeQuery(sql);
            while (res.next()) {
            alamat.setText(res.getString("alamat"));
            notelp.setText(res.getString("notelp"));
          
            
            
        }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Gagal");
        }
        
    }//GEN-LAST:event_namacomboActionPerformed

    private void namacomboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namacomboMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namacomboMouseClicked

    private void idcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcomActionPerformed
        // TODO add your handling code he:
         String id = (String) idcom.getSelectedItem();
        Connection con = koneksi.getKoneksi();
        try {
            String sql = "SELECT * FROM datazakat WHERE id_zakat='" + id+"'";

            Statement sta = (Statement) con.createStatement();
            ResultSet res = sta.executeQuery(sql);
            while (res.next()) {
            besarzakat.setText(res.getString("besar_zakat"));

        
        }
          
        
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Gagal");
        }
        
    }//GEN-LAST:event_idcomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penyaluranzakat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton bersihkan;
    private javax.swing.JTextField besarzakat;
    private javax.swing.JButton btncari;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JComboBox<String> idcom;
    private javax.swing.JTextField idsalur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kembali;
    private javax.swing.JComboBox<String> namacombo;
    private javax.swing.JTextField notelp;
    private javax.swing.JButton pendatan;
    private javax.swing.JButton print;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabsalur;
    private javax.swing.JFormattedTextField tanggal;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
